spring:
  h2 :
    console.enabled : true
    console :
      path : "/h2"
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:h2:mem:attornatusdb
    username: attornatus
    password: attornatus123
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /api
